"""Environment config loader.

Reads `metaflow_extensions/remote_step/environments/<env>.json`, generated by
`terraform output -json remote_step_config`. Package data — no runtime SSM
lookup, no AWS call to read configuration.
"""

from __future__ import annotations

from dataclasses import dataclass
import json
import os
from pathlib import Path

from remote_step.errors import ConfigError


REQUIRED_KEYS = (
    "region",
    "payload_bucket",
    "fargate_queue",
    "ec2_cpu_queue",
    "ec2_gpu_queue",
    "job_role_arn",
    "job_execution_role_arn",
    "runner_image",
    "log_group",
)


@dataclass(frozen=True)
class RemoteStepConfig:
    """Resolved config for one environment (dev, prod, ...)."""

    env_name: str
    region: str
    payload_bucket: str
    fargate_queue: str
    ec2_cpu_queue: str
    ec2_gpu_queue: str
    job_role_arn: str
    job_execution_role_arn: str
    runner_image: str
    log_group: str
    # ARN of the IAM role in our account that Outerbounds' pod task role can
    # sts:AssumeRole into, so non-@remote_step pods (which live in the
    # Outerbounds AWS account and can't read our bucket directly) can lazy-
    # load RemoteArtifact refs via a role hop. Empty string when absent.
    artifact_read_role_arn: str = ""


def _config_dir() -> Path:
    """Directory containing shipped env JSON files."""
    return Path(__file__).parent / "environments"


def available_envs() -> list[str]:
    """List env names that have a shipped JSON file."""
    d = _config_dir()
    if not d.exists():
        return []
    return sorted(p.stem for p in d.glob("*.json"))


def load(env_name: str | None = None) -> RemoteStepConfig:
    """Load config for the given env, or `$REMOTE_STEP_ENV`, or 'dev'.

    Raises:
        ConfigError with an actionable message on missing file / missing keys.
    """
    env_name = env_name or os.environ.get("REMOTE_STEP_ENV", "dev")
    path = _config_dir() / f"{env_name}.json"
    if not path.exists():
        available = available_envs()
        avail_str = ", ".join(available) if available else "(none)"
        raise ConfigError(
            f"env config not found: {path}\n"
            f"  available envs: {avail_str}\n"
            f"  generate with: cd infra && terraform apply && "
            f"terraform output -json remote_step_config > "
            f"metaflow_extensions/remote_step/environments/{env_name}.json",
            env_name=env_name,
            path=str(path),
        )
    try:
        body = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ConfigError(
            f"{path} is not valid JSON: {exc}",
            env_name=env_name,
        ) from exc
    if not isinstance(body, dict):
        raise ConfigError(
            f"{path}: expected top-level JSON object, got {type(body).__name__}",
            env_name=env_name,
        )
    missing = [k for k in REQUIRED_KEYS if k not in body]
    if missing:
        raise ConfigError(
            f"{path} missing required keys: {missing}\n"
            f"  regenerate from terraform output",
            env_name=env_name,
            missing_keys=missing,
        )
    return RemoteStepConfig(
        env_name=env_name,
        region=body["region"],
        payload_bucket=body["payload_bucket"],
        fargate_queue=body["fargate_queue"],
        ec2_cpu_queue=body["ec2_cpu_queue"],
        ec2_gpu_queue=body["ec2_gpu_queue"],
        job_role_arn=body["job_role_arn"],
        job_execution_role_arn=body["job_execution_role_arn"],
        runner_image=body["runner_image"],
        log_group=body["log_group"],
        artifact_read_role_arn=body.get("artifact_read_role_arn", ""),
    )


def queue_for(cfg: RemoteStepConfig, queue_kind: str) -> str:
    """Map 'fargate' | 'ec2_cpu' | 'ec2_gpu' → queue ARN/name from config."""
    mapping = {
        "fargate": cfg.fargate_queue,
        "ec2_cpu": cfg.ec2_cpu_queue,
        "ec2_gpu": cfg.ec2_gpu_queue,
    }
    if queue_kind not in mapping:
        raise ConfigError(f"unknown queue kind: {queue_kind!r}")
    return mapping[queue_kind]
