"""Cluster config loader.

Reads `metaflow_extensions/remote_step/config.json`, generated by
`terraform output -json remote_step_config`. Package data — no runtime SSM
lookup, no AWS call to read configuration.

One cluster, one config file. There is deliberately no dev/prod split: the
infrastructure is a single cluster partitioned by Kueue ClusterQueue per
team, so a second config would describe something that does not exist.
"""

from __future__ import annotations

from dataclasses import dataclass, field
import json
from pathlib import Path

from remote_step.errors import ConfigError


REQUIRED_KEYS = (
    "region",
    "cluster_name",
    "cluster_endpoint",
    "payload_bucket",
    "runner_image",
    "log_group",
    "local_queue",
    "service_account",
    "submitter_role_arn",
)


@dataclass(frozen=True)
class RemoteStepConfig:
    """Resolved config for one environment."""

    region: str

    # --- cluster ---
    cluster_name: str
    # Shipped rather than discovered: saves an eks:DescribeCluster call per
    # step. The driver still needs DescribeCluster for the CA bundle, so this
    # is a latency optimisation, not the only source.
    cluster_endpoint: str

    # --- storage / image / logs ---
    payload_bucket: str
    runner_image: str
    log_group: str

    # --- Kueue ---
    # LocalQueue name, identical in every team namespace. The namespace is
    # what selects the team's ClusterQueue and therefore its quota.
    local_queue: str

    # --- identity ---
    # ServiceAccount the runner pod runs as. Bound to the runner IAM role by
    # an EKS Pod Identity association, so the pod gets AWS credentials with
    # no static secret and no role ARN in the pod spec.
    service_account: str
    # Role the Outerbounds driver assumes to reach the cluster API. Its EKS
    # access entry is scoped to the team namespaces.
    submitter_role_arn: str
    # Baked into every RemoteArtifact ref so a downstream non-@remote_step
    # consumer on an Outerbounds pod can hop into this account to read it.
    artifact_read_role_arn: str = ""

    # Namespaces that exist as team namespaces. Advisory: used to fail fast
    # with a good message when a step names a team that has no namespace,
    # rather than getting a 403 from the API server.
    teams: tuple[str, ...] = field(default_factory=tuple)


CONFIG_FILENAME = "config.json"


def config_path() -> Path:
    """Location of the shipped config file."""
    return Path(__file__).parent / CONFIG_FILENAME


def load() -> RemoteStepConfig:
    """Load the cluster config.

    Raises:
        ConfigError with an actionable message on missing file / missing keys.
    """
    path = config_path()
    if not path.exists():
        raise ConfigError(
            f"config not found: {path}\n"
            f"  generate with: cd infra/eks && "
            f"terraform output -json remote_step_config > "
            f"src/metaflow_extensions/remote_step/{CONFIG_FILENAME}",
            path=str(path),
        )
    try:
        body = json.loads(path.read_text())
    except json.JSONDecodeError as exc:
        raise ConfigError(f"{path} is not valid JSON: {exc}") from exc
    if not isinstance(body, dict):
        raise ConfigError(
            f"{path}: expected top-level JSON object, got {type(body).__name__}"
        )
    missing = [k for k in REQUIRED_KEYS if k not in body]
    if missing:
        # An old config file is the likeliest reason for a miss, and
        # "regenerate from terraform" is not an obvious fix unless you know
        # the schema changed — so name the dead keys when they are present.
        stale = [
            k
            for k in (
                "fargate_queue",
                "ec2_cpu_queue",
                "ec2_gpu_queue",
                "job_role_arn",
                "job_execution_role_arn",
            )
            if k in body
        ]
        hint = ""
        if stale:
            hint = (
                f"\n  this config predates the EKS migration (found {stale}); "
                f"regenerate it from infra/eks"
            )
        raise ConfigError(
            f"{path} missing required keys: {missing}{hint}",
            missing_keys=missing,
        )
    return RemoteStepConfig(
        region=body["region"],
        cluster_name=body["cluster_name"],
        cluster_endpoint=body["cluster_endpoint"],
        payload_bucket=body["payload_bucket"],
        runner_image=body["runner_image"],
        log_group=body["log_group"],
        local_queue=body["local_queue"],
        service_account=body["service_account"],
        submitter_role_arn=body["submitter_role_arn"],
        artifact_read_role_arn=body.get("artifact_read_role_arn", ""),
        teams=tuple(body.get("teams", ())),
    )


def check_team(cfg: RemoteStepConfig, team: str) -> None:
    """Fail fast if `team` has no namespace in this cluster.

    Only advisory — `teams` is a snapshot from terraform, so a namespace
    added after the config was generated would be rejected here even though
    it exists. That is why an empty `teams` skips the check entirely rather
    than refusing everything.
    """
    if not cfg.teams:
        return
    if team not in cfg.teams:
        raise ConfigError(
            f"team={team!r} has no namespace in cluster {cfg.cluster_name}.\n"
            f"  known teams: {', '.join(cfg.teams)}\n"
            f"  add it to var.teams in infra/eks and re-apply, then "
            f"regenerate this env config.",
            team=team,
            known_teams=list(cfg.teams),
        )
